#include <kernel.h>
#include <device.h>
#include <init.h>
#include <sys/sys_io.h>
#include <devicetree.h>
#include <autoconf.h>
#include <pinmux/stm32/pinmux_stm32.h>

static const struct pin_config pinconf[] = {

/**
 * USART
 */
#if DT_NODE_HAS_STATUS(DT_NODELABEL(usart1), okay) && CONFIG_SERIAL
        {STM32_PIN_PA9, STM32F4_PINMUX_FUNC_PA9_USART1_TX},
        {STM32_PIN_PA10, STM32F4_PINMUX_FUNC_PA10_USART1_RX},
#endif
#if DT_NODE_HAS_STATUS(DT_NODELABEL(usart2), okay) && CONFIG_SERIAL
        {STM32_PIN_PD5, STM32F4_PINMUX_FUNC_PD5_USART2_TX},
        {STM32_PIN_PD5, STM32F4_PINMUX_FUNC_PA3_USART2_RX},
#endif
#if DT_NODE_HAS_STATUS(DT_NODELABEL(usart3), okay) && CONFIG_SERIAL
        {STM32_PIN_PD8, STM32F4_PINMUX_FUNC_PD8_USART3_TX},
        {STM32_PIN_PD9, STM32F4_PINMUX_FUNC_PD9_USART3_RX},
#endif
#if DT_NODE_HAS_STATUS(DT_NODELABEL(usart6), okay) && CONFIG_SERIAL
        {STM32_PIN_PC6, STM32F4_PINMUX_FUNC_PC6_USART6_TX},
        {STM32_PIN_PC7, STM32F4_PINMUX_FUNC_PC7_USART6_RX},
#endif

/**
 * I2C
 */
#if DT_NODE_HAS_STATUS(DT_NODELABEL(i2c1), okay) && CONFIG_I2C
        {STM32_PIN_PB6, STM32F4_PINMUX_FUNC_PB6_I2C1_SCL},
        {STM32_PIN_PB7, STM32F4_PINMUX_FUNC_PB7_I2C1_SDA},
#endif

/**
 * SPI
 */
#if DT_NODE_HAS_STATUS(DT_NODELABEL(spi1), okay) && CONFIG_SPI
#ifdef CONFIG_SPI_STM32_USE_HW_SS
        {STM32_PIN_PA4, STM32F4_PINMUX_FUNC_PA4_SPI1_NSS},
#endif
        {STM32_PIN_PA5, STM32F4_PINMUX_FUNC_PA5_SPI1_SCK},
        {STM32_PIN_PA6, STM32F4_PINMUX_FUNC_PA6_SPI1_MISO},
        {STM32_PIN_PB5, STM32F4_PINMUX_FUNC_PB5_SPI1_MOSI},
#endif

#if DT_NODE_HAS_STATUS(DT_NODELABEL(spi2), okay) && CONFIG_SPI
#ifdef CONFIG_SPI_STM32_USE_HW_SS
        {STM32_PIN_PB12, STM32F4_PINMUX_FUNC_PB12_SPI2_NSS},
#endif
        {STM32_PIN_PB10, STM32F4_PINMUX_FUNC_PB10_SPI2_SCK},
        {STM32_PIN_PC2, STM32F4_PINMUX_FUNC_PC2_SPI2_MISO},
        {STM32_PIN_PC3, STM32F4_PINMUX_FUNC_PC3_SPI2_MOSI},
#endif

/**
 * Ethernet
 */
#if CONFIG_ETH_STM32_HAL
        {STM32_PIN_PC1, STM32F4_PINMUX_FUNC_PC1_ETH},
        {STM32_PIN_PC4, STM32F4_PINMUX_FUNC_PC4_ETH},
        {STM32_PIN_PC5, STM32F4_PINMUX_FUNC_PC5_ETH},

        {STM32_PIN_PA1, STM32F4_PINMUX_FUNC_PA1_ETH},
        {STM32_PIN_PA2, STM32F4_PINMUX_FUNC_PA2_ETH},
        {STM32_PIN_PA7, STM32F4_PINMUX_FUNC_PA7_ETH},

        {STM32_PIN_PB11, STM32F4_PINMUX_FUNC_PB11_ETH},
        {STM32_PIN_PB12, STM32F4_PINMUX_FUNC_PB12_ETH},
        {STM32_PIN_PB13, STM32F4_PINMUX_FUNC_PB13_ETH},
#endif
};

static int pinmux_init(struct device *port) {
    ARG_UNUSED(port);
    stm32_setup_pins(pinconf, ARRAY_SIZE(pinconf));
    return 0;
}

SYS_INIT(pinmux_init, PRE_KERNEL_1, CONFIG_PINMUX_STM32_DEVICE_INITIALIZATION_PRIORITY);